services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planning_poker_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - planning_poker_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: planning_poker_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - planning_poker_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: planning_poker_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: planning_poker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: planning_poker
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - planning_poker_network

networks:
  planning_poker_network:
    driver: bridge

volumes:
  dbdata:
    driver: local

